# =======================================
#               ‚ö° WASHERE ‚ö°
#                By Levaii
# =======================================



# =======================================
#           GENERAL SETTINGS
# =======================================
server-type: none  # Options: survival, lobby (ffa coming soon)

# =======================================
#           STORAGE SETTINGS
# =======================================
storage:
  type: "yaml"  # Options: yaml, mysql

mysql:
  host: "127.0.0.1"
  port: 3306
  database: "washeresettings"
  username: "root"
  password: "password"

# =======================================
#           PLAYER SETTINGS
#             ( LOBBY MODE )
# =======================================
jump-velocity: 1.2
fall-limit: -30.0

# =======================================
#            CHAT SETTINGS
# =======================================
join-message: "&a&l+ &r%washere_tag_prefix%&r%luckperms_prefix%%player_displayname%&r%washere_tag_suffix% &7 ú·¥ÄÍú± ·¥ä·¥è…™…¥·¥á·¥Ö ·¥õ ú·¥á Íú±·¥á Ä·¥†·¥á Ä!"
leave-message: "&c&l- &r%washere_tag_prefix%&r%luckperms_prefix%%player_displayname%&r%washere_tag_suffix% &7 ú·¥ÄÍú±  ü·¥áÍú∞·¥õ ·¥õ ú·¥á Íú±·¥á Ä·¥†·¥á Ä!"
chat:
  format: "%washere_tag_prefix%%luckperms_prefix%%luckperms_meta_color%%player_name%%washere_tag_suffix%&f: %message%"

# =======================================
#       COMMAND FILTER SETTINGS
#    (COMMANDS TAB SUGGESTIONS )
# =======================================
# Commands to suggest in the tab completion
filtered-commands:
  - help
  - settings
  - profile
  - msg
  - reply
  - r
  - tags

op-bypass: true

# By default, minecraft will block commands if the player doesn't have permission for that command,
# so it's not necessary unless you want a custom message.
blocked-commands:
  - plugins
  - pl
  - bukkit:pl
  - bukkit:plugins
  - version
  - ver
  - bukkit:ver
  - bukkit:version
  - about
  - bukkit:about
  - help
  - bukkit:help
  - "?"
  - "bukkit:?"

# =======================================
#           DISPLAY SETTINGS
# =======================================
# ----- SCOREBOARD CONFIGURATION -----
scoreboard:
  title: "&6·¥°·¥ÄÍú± ú·¥á Ä·¥á"
  lines:
    - "     &7&o·¥°·¥ÄÍú± ú·¥á Ä·¥á·¥ç·¥Ñ.·¥ç·¥á      "
    - ""
    - "&7…¥·¥Ä·¥ç·¥á: &r%luckperms_meta_color%%player_displayname%"
    - "&7 Ä·¥Ä…¥·¥ã: &r%luckperms_prefix%"
    - "&7·¥ò…™…¥…¢: &a%player_ping%·¥çÍú±"
    - ""
    - "&7üåç ·¥è…¥ ü…™…¥·¥á: &6%server_online%"
    - ""
    - "&8&o%server_time_dd.MM.yyyy%"

  # ----- TAB SORTING CONFIGURATION & NAME TAG COLOR -----
  teams:
    founder:
      prefix : "&4"
      priority: 1 #RANK WEIGHT
    vip:
      prefix: "&6"
      priority: 2
    default:
      prefix: "&7"
      priority: 3

# ----- TABLIST CONFIGURATION -----
tablist:
  player-list-name-format: "%washere_tag_prefix%%luckperms_prefix%%player_displayname%%washere_tag_suffix%"
  header: |
    
    &6·¥°·¥ÄÍú± ú·¥á Ä·¥á
    &7&o·¥á…¥·¥ä·¥è Ä  è·¥è·¥ú Ä Íú±·¥õ·¥Ä è ·¥Ä…¥·¥Ö  ú·¥Ä·¥†·¥á Íú∞·¥ú…¥!

  footer: |
    
    &7…¥·¥á·¥á·¥Ö  ú·¥á ü·¥ò? ·¥õ è·¥ò·¥á &e/ ú·¥á ü·¥ò

# =======================================
#        SERVER CONNECTION SETTINGS
#             ( LOBBY COMPASS )
# =======================================
servers:
  Survival:
    ip: "127.0.0.1"
    port: 25566
  FFA:
    ip: "127.0.0.1"
    port: 25567

# =======================================
#           WARP CONFIGURATION
# =======================================
warps:
  enabled: true
  max-per-player: 1
  public-warps-enabled: true
  cooldown: 3